// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/temperature.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/temperature.proto

It has these top-level messages:
	City
	Temperature
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google.golang.org/protobuf/types/known/timestamppb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type City struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *City) Reset()                    { *m = City{} }
func (m *City) String() string            { return proto.CompactTextString(m) }
func (*City) ProtoMessage()               {}
func (*City) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Temperature struct {
	TemmpInfos  []*Temperature_TempInfo    `protobuf:"bytes,4,rep,name=temmpInfos" json:"temmpInfos,omitempty"`
	LastUpdated *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
}

func (m *Temperature) Reset()                    { *m = Temperature{} }
func (m *Temperature) String() string            { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()               {}
func (*Temperature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Temperature) GetTemmpInfos() []*Temperature_TempInfo {
	if m != nil {
		return m.TemmpInfos
	}
	return nil
}

func (m *Temperature) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Temperature_TempRange struct {
	Max int32 `protobuf:"varint,1,opt,name=Max,json=max" json:"Max,omitempty"`
	Min int32 `protobuf:"varint,2,opt,name=Min,json=min" json:"Min,omitempty"`
}

func (m *Temperature_TempRange) Reset()                    { *m = Temperature_TempRange{} }
func (m *Temperature_TempRange) String() string            { return proto.CompactTextString(m) }
func (*Temperature_TempRange) ProtoMessage()               {}
func (*Temperature_TempRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Temperature_TempRange) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Temperature_TempRange) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

type Temperature_TempInfo struct {
	Day      string                 `protobuf:"bytes,3,opt,name=Day,json=day" json:"Day,omitempty"`
	TempRang *Temperature_TempRange `protobuf:"bytes,4,opt,name=tempRang" json:"tempRang,omitempty"`
}

func (m *Temperature_TempInfo) Reset()                    { *m = Temperature_TempInfo{} }
func (m *Temperature_TempInfo) String() string            { return proto.CompactTextString(m) }
func (*Temperature_TempInfo) ProtoMessage()               {}
func (*Temperature_TempInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *Temperature_TempInfo) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *Temperature_TempInfo) GetTempRang() *Temperature_TempRange {
	if m != nil {
		return m.TempRang
	}
	return nil
}

func init() {
	proto.RegisterType((*City)(nil), "temperature.City")
	proto.RegisterType((*Temperature)(nil), "temperature.Temperature")
	proto.RegisterType((*Temperature_TempRange)(nil), "temperature.Temperature.TempRange")
	proto.RegisterType((*Temperature_TempInfo)(nil), "temperature.Temperature.TempInfo")
}

func init() { proto.RegisterFile("protobuf/temperature.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x6b, 0x83, 0x40,
	0x10, 0xc5, 0x6b, 0x34, 0x6d, 0x32, 0x86, 0xd2, 0xee, 0x69, 0xd9, 0x4b, 0xad, 0x27, 0x4f, 0x2b,
	0xd8, 0x73, 0x5b, 0xfa, 0x07, 0x42, 0x0b, 0xbd, 0x2c, 0xf6, 0x52, 0x0a, 0x65, 0x83, 0x13, 0x11,
	0xb2, 0x2a, 0xba, 0x42, 0xfc, 0x32, 0xfd, 0xac, 0xc5, 0x35, 0x26, 0xb6, 0xd0, 0xdc, 0x1e, 0xcf,
	0x37, 0xcf, 0xdf, 0xcc, 0x02, 0x2b, 0xab, 0x42, 0x17, 0xab, 0x66, 0x1d, 0x6a, 0x54, 0x25, 0x56,
	0x52, 0x37, 0x15, 0x72, 0x63, 0x12, 0x77, 0x64, 0xb1, 0xab, 0xb4, 0x28, 0xd2, 0x0d, 0x86, 0x87,
	0x7c, 0xa6, 0xb0, 0xd6, 0x52, 0x95, 0x7d, 0xda, 0x67, 0xe0, 0x3c, 0x65, 0xba, 0x25, 0x04, 0x9c,
	0x5c, 0x2a, 0xa4, 0x96, 0x67, 0x05, 0x73, 0x61, 0xb4, 0xff, 0x3d, 0x01, 0x37, 0x3e, 0x94, 0x91,
	0x07, 0x00, 0x8d, 0x4a, 0x95, 0x2f, 0xf9, 0xba, 0xa8, 0xa9, 0xe3, 0xd9, 0x81, 0x1b, 0x5d, 0xf3,
	0x31, 0x41, 0xfc, 0x47, 0x77, 0x49, 0x31, 0x1a, 0x22, 0xb7, 0xb0, 0xd8, 0xc8, 0x5a, 0x7f, 0x35,
	0x65, 0x22, 0x35, 0x26, 0x74, 0xea, 0x59, 0x81, 0x1b, 0x31, 0xde, 0x63, 0xf2, 0x01, 0x93, 0xc7,
	0x03, 0xa6, 0x70, 0xbb, 0xfc, 0x7b, 0x1f, 0x67, 0x21, 0xcc, 0xbb, 0x5a, 0x21, 0xf3, 0x14, 0xc9,
	0x05, 0xd8, 0x6f, 0x72, 0x6b, 0x88, 0xa7, 0xc2, 0x56, 0x72, 0x6b, 0x9c, 0x2c, 0xa7, 0x93, 0x9d,
	0x93, 0xe5, 0xec, 0x13, 0x66, 0x03, 0x47, 0xf7, 0xf5, 0x59, 0xb6, 0xd4, 0x36, 0x1b, 0xda, 0x89,
	0x6c, 0xc9, 0x1d, 0xcc, 0xf4, 0xae, 0x8e, 0x3a, 0x86, 0xc4, 0x3f, 0xba, 0x8e, 0xf9, 0xaf, 0xd8,
	0xcf, 0x44, 0xaf, 0x70, 0xb6, 0xac, 0x10, 0x35, 0x56, 0xe4, 0x1e, 0xce, 0x97, 0xa8, 0xc7, 0xd7,
	0xba, 0xfc, 0x55, 0xd5, 0x1d, 0x99, 0xd1, 0xff, 0xda, 0xfd, 0x93, 0xc7, 0xc5, 0x07, 0xf0, 0xfd,
	0x33, 0xad, 0x4e, 0x8d, 0xba, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x66, 0x10, 0x99, 0x8d, 0xe9,
	0x01, 0x00, 0x00,
}
